package model;
// Generated 05/02/2014 02:37:50 by Hibernate Tools 3.6.0



/**
 * Filmes generated by hbm2java
 */
public class Filmes  implements java.io.Serializable {


     private Integer idfilmes;
     private String titulo;
     private String descricao;
     private String genero;
     private String autor;
     private String disponibilidade;
     private String imagemurl;
     private int duracao;

    public Filmes() {
    }

    public Filmes(String titulo, String descricao, String genero, String autor, String disponibilidade, String imagemurl, int duracao) {
       this.titulo = titulo;
       this.descricao = descricao;
       this.genero = genero;
       this.autor = autor;
       this.disponibilidade = disponibilidade;
       this.imagemurl = imagemurl;
       this.duracao = duracao;
    }
   
    public Integer getIdfilmes() {
        return this.idfilmes;
    }
    
    public void setIdfilmes(Integer idfilmes) {
        this.idfilmes = idfilmes;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getDisponibilidade() {
        return this.disponibilidade;
    }
    
    public void setDisponibilidade(String disponibilidade) {
        this.disponibilidade = disponibilidade;
    }
    public String getImagemurl() {
        return this.imagemurl;
    }
    
    public void setImagemurl(String imagemurl) {
        this.imagemurl = imagemurl;
    }
    public int getDuracao() {
        return this.duracao;
    }
    
    public void setDuracao(int duracao) {
        this.duracao = duracao;
    }




}


