package model;
// Generated 05/02/2014 02:37:50 by Hibernate Tools 3.6.0



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idusuarios;
     private String nome;
     private String sobrenome;
     private String email;
     private String senha;
     private String confSenha;

    public Usuarios() {
    }

    public Usuarios(String nome, String sobrenome, String email, String senha, String confSenha) {
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.email = email;
       this.senha = senha;
       this.confSenha = confSenha;
    }
   
    public Integer getIdusuarios() {
        return this.idusuarios;
    }
    
    public void setIdusuarios(Integer idusuarios) {
        this.idusuarios = idusuarios;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getConfSenha() {
        return this.confSenha;
    }
    
    public void setConfSenha(String confSenha) {
        this.confSenha = confSenha;
    }




}


